language: objective-c
os: osx
osx_image: xcode9.2
sudo: required
python: '3.6'
git:
  depth: 3
branches:
  only:
  - master
env:
  global:
  - BUILD_VERSION="0.0.2"
  - secure: hMJTTD9VTq0Fzb8Ok1G1yIVYPiwOJgzV5l2snS+ji/gQM5YnpR5SXiUyisA8TpKfAHJdFEPnzvCuw+aOR68SPn3ShPqvy4ea/EAoPfEgpcADOAciFy3cFL5wjNy9clEY1xMdIFHOruAvJwfda5KByCEdXUuZIq5dSuLI2uiNX4n6EqQueR/kO+ukAIE4vFkB5nEPf1da3irQLmHk6EDBqIs4ktLhW1B8s3yqpA0kRxx5e3XvnhR36Jab5f8RsnhObvy4IrYzO0Xcukx1VvVfEv0ThmeHk5MUt0McQJT67y+5f8CbvarpFF+J1DrguAxNf+z4mi3ohPjHOvrhLLze4VYguEBe6z4X2gxuWxKcErn+4xxigtsH002NlbXWj8tg13e8U7Qe32bM4xrjYLEKIb5xf9N1+MuT8LtXsYWnRq9KV0PYnqj59qXVo/9pYmuB0DLqGxIKHQFakMb/xjy5WYA4UMSp0enwVLt+e1S/ZLy+UuouwhaYjJLfid6wwx4EwlRszTESpZgd4PKGh7PvUem+DBtbiCIpx8GcMXULbd31ZBNrOtwK3zlOAJQpVCxEmrentmC/jpBfxYQg9AbbHbTyl35lHt4t+NCFNxdiSkjYx0f1MVgDGDW7h81n3T2vu8m526IxpFXCaoKGHWbXv8t/A+bmrc3tgZGNDM3aqms=
before_install:
- brew install python3
- sudo python3 -m pip install -U pip
- python3 -m pip install pyinstaller pyqt5-sip pyqt5
- npm install -g appdmg
install:
- echo "Install Done!"
script:
- cd packaging/pyinstaller
- rm -rf build
- rm -rf dist
- python3 -m PyInstaller --clean contextually.osx.spec
- appdmg dmg.json Contextually-${BUILD_VERSION}-macOS.dmg
- mv Contextually-${BUILD_VERSION}-macOS.dmg "${TRAVIS_BUILD_DIR}"
- echo "Done!"
notifications:
  email: false
before_deploy:
- git config --local user.name "jkhan-007"
- git config --local user.email "imon.bot@gmail.com"
- git remote set-url origin https://jkhan-007:${GITHUB_TOKEN}@github.com/jkhan-007/contextually-app.git
- git push origin :refs/tags/${BUILD_VERSION}
- git tag -f -am v${BUILD_VERSION} ${BUILD_VERSION}
deploy:
  provider: releases
  file: "${TRAVIS_BUILD_DIR}/Contextually-${BUILD_VERSION}-macOS.dmg"
  overwrite: true
  skip_cleanup: true
  on:
    repo: jkhan-007/contextually-app
  api-key:
    secure: T/wwJAnH+VbZlOBpaOYB5bfGnxFF03z2Ia4Ohyrtf4y1T0YXaDZPqhSTQQ8kFZOR3rIPpWXBryGmMhAfh1z/82ol8fyDu2zkaEBHLhpKOqj+CW0re3CGB8v41LdNYr7h2apfdqNjuKbpWERC+p2eo/X1PXRG2Mjzn82/MJymZW8H4ZasjzPhRgjXYt9hJZYhXf9vB7Jrl5s/WrnfLmIzVzWpKuwuZgeTWQLmEF5dnSLmUVo1twZnoTMCvW6sgrnk1eZAxoGgbD1/v+e+ppkbO+cnlw67PTUrPrihIrLm/nwFbuxB/BepR3SLsreUCV+baUPMQXchrgtpjruQ7sYU9ucmYM5mvmbTngHH05MiJFGCMTLqp/NosCGT5ih9zo8o9Oo3zeZzkvcHvRuGTpw81pIRKSWzgrjPSZWUVbRZ+ThRqFj7Y90ucXNzP2p6Mt3vPVVicjVEU5G7mzf6q1WkVb6D/bCKNX0z1C/DWIlC4+GQbK5uruylVUA9vJneyfH/7p39zJSgi2pskTILOZ5Zr/QJkdUwjY5IQaRT8LkgUtBU9MyPaNawZRyK4adCQxvoEnDzY/srK/aspeYv10q7eCJRtBKMotQPt/ID1wuQBrKwHA0v5mPaa0XilH8Gu2MSa9kpKF8egogEPjHJqLOqIWL5WG4DxPtxa+evCycfdyM=
